Bugfix/user agent init
ls1intum/Orion pull request #25
Opened 2020-09-20 20:53 UTC by ungaralex

Fixes the initialisation of the user agent in the embedded browser for new installs. Previously, the default value of `null`could cause crashes, or just a failed load of the Artemis website.

I also bumped the version compatibility to IntelliJ 2020.2.2

For testing, please install: [orion-1.0.2.zip](https://github.com/ls1intum/Orion/files/5252600/orion-1.0.2.zip)

2020-09-28 08:18 UTC, sleiss requested changes
I'm using Idea 2020.2.2 and for me, it crashed when opening the Artemis tab:
![Peek 2020-09-28 10-17](https://user-images.githubusercontent.com/5084100/94407618-f3517200-0173-11eb-9d9e-2d1060a82143.gif)
I also had Orion 1.0.1 previously installed.
I'm using Ubuntu 20.04.

2020-09-28 08:53 UTC, krusche commented
Same for me. Unfortunately, it is still crashing.

Here is the crash report. Maybe it helps:

Process:               idea [68673]
Path:                  /Applications/IntelliJ IDEA.app/Contents/MacOS/idea
Identifier:            com.jetbrains.intellij
Version:               2020.2.2 (IU-202.7319.50)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           idea [68673]
User ID:               501

Date/Time:             2020-09-28 10:51:56.569 +0200
OS Version:            Mac OS X 10.15.6 (19G2021)
Report Version:        12
Bridge OS Version:     4.6 (17P6610)
Anonymous UUID:        576FFCF9-2A60-C423-39B4-870E44844B4C

Sleep/Wake UUID:       75DD1E0C-2857-4DEB-9530-A3E1B29D5EF3

Time Awake Since Boot: 870000 seconds
Time Since Wake:       130000 seconds

System Integrity Protection: enabled

Crashed Thread:        112  WebCore: LocalStorage

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000004c
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x4c:
--> 
    __TEXT                 0000000106b54000-0000000106b5a000 [   24K] r-x/rwx SM=COW  /Applications/IntelliJ IDEA.app/Contents/MacOS/idea

Application Specific Information:
abort() called

Thread 0:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libjfxwebkit.dylib            	0x0000000161bb3cd6 JSC::CodeBlock::finishCreation(JSC::VM&, JSC::ScriptExecutable*, JSC::UnlinkedCodeBlock*, JSC::JSScope*) + 8918
1   libjfxwebkit.dylib            	0x00000001623d7f7f JSC::ScriptExecutable::newCodeBlockFor(JSC::CodeSpecializationKind, JSC::JSFunction*, JSC::JSScope*, JSC::JSObject*&) + 607
2   libjfxwebkit.dylib            	0x00000001623d86d0 JSC::ScriptExecutable::prepareForExecutionImpl(JSC::VM&, JSC::JSFunction*, JSC::JSScope*, JSC::CodeSpecializationKind, JSC::CodeBlock*&) + 256
3   libjfxwebkit.dylib            	0x00000001620db1f0 JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*) + 912

2020-09-28 08:58 UTC, krusche commented
It also kept crashing at startup time. It only helped to manually remove the plugin from the IntelliJ plugin folder

2020-09-28 09:02 UTC, sleiss commented
> It also kept crashing at startup time. It only helped to manually remove the plugin from the IntelliJ plugin folder

That's not the case for me. As long as I don't open the Artemis tab, everything seems to work fine.

2020-09-28 09:11 UTC, krusche commented
The tab was open at startup time and I had no chance to close it ;-)

2020-10-03 00:21 UTC, nutatuna commented
The plugin runs fine in sandbox environment, but it keeps crashing on my IDE. The problem seems to be related to JavaFX failing to load. Idea.log shows this:
`2020-10-03 02:12:27,079 [ 313849]   INFO - STDERR - InteropFactory: cannot load com.sun.javafx.embed.swing.newimpl.InteropFactoryN`
after every crash.

There are some other people who have the same problem in this thread: [https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009499240-JavaFX-Runtime-for-Plugins-Crash-when-Plugin-activation-on-IDEA-CE2020-2](url)

2020-10-22 10:52 UTC, closed without merging

2020-10-22 10:53 UTC, ungaralex commented
Closed since #27 takes care of this