[Feature] Assessment in Orion
ls1intum/Orion pull request #64
Opened 2021-08-13 16:46 UTC by MDK5

### Motivation and Context
Enables editing inline comments in Orion. Requires https://github.com/ls1intum/Artemis/pull/3913.

### Description
Adds a new OrionAssessmentService which handles the feedback internally and an OrionEditorProvider to provide the OrionAssessmentEditor with the ability to edit the assessment.

### Limitations
The following features/problems will be adressed in a followup
 - Assessing Feedback requests, complaints and exams
 - The web client layout does currently not deal with the small Orion window well
 - There is a strange bug that prevents certain key events (like enter, arrow keys) from reaching the inline comments

### Steps for Testing

1.  Install the release as described in [the readme](https://github.com/ls1intum/Orion/blob/master/README.md#testing-of-pull-requests)
2.  Deploy the Artemis PR on a testserver and set your Orion to connect to the testserver
3.  Create/Locate a programming exercise with submissions
4.  Assess the exercise in Orion
5.  Edit the assessment in various ways
6.  Edit the code and execute it locally
7.  Save/Submit the assessment
8.  Confirm the assessment was saved correctly by checking it in the web client
9.  Assess another submission

### Screenshots
TODO

2021-08-19 14:18 UTC, MaisiKoleni commented
Problems when installing first time on 212.* version:
```
java.lang.UnsupportedOperationException: Failed to map LightVirtualFile: \What's New in IntelliJ IDEA (filesystem com.intellij.testFramework.LightVirtualFileBase$MyVirtualFileSystem@4bfea755) into nio Path
	at com.intellij.openapi.vfs.VirtualFile.toNioPath(VirtualFile.java:162)
	at de.tum.www1.orion.ui.assessment.OrionEditorProvider.accept(OrionEditorProvider.kt:27)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.lambda$getProviders$0(FileEditorProviderManagerImpl.java:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.lambda$getProviders$1(FileEditorProviderManagerImpl.java:47)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:146)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.getProviders(FileEditorProviderManagerImpl.java:47)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.dumbModeFinished(FileEditorManagerImpl.java:279)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$1.lambda$exitDumbMode$0(FileEditorManagerImpl.java:182)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

2021-08-19 14:42 UTC, MaisiKoleni commented
Problem when opening a student class in version 212.*:
```
java.lang.NoClassDefFoundError: com/intellij/util/ui/codereview/diff/EditorComponentInlaysManager
	at de.tum.www1.orion.ui.assessment.OrionAssessmentEditor.initializeFeedback(OrionAssessmentEditor.kt:52)
	at de.tum.www1.orion.ui.assessment.OrionAssessmentEditor.<init>(OrionAssessmentEditor.kt:27)
	at de.tum.www1.orion.ui.assessment.OrionEditorProvider.createEditor(OrionEditorProvider.kt:60)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:997)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:969)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1786)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:968)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:456)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:965)
	at com.jetbrains.rdserver.editors.BackendServerFileEditorManager.openFileImpl4(BackendServerFileEditorManager.kt:63)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$14(FileEditorManagerImpl.java:891)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:890)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:764)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:731)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openEditorImpl$22(FileEditorManagerImpl.java:1269)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl(FileEditorManagerImpl.java:1263)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileEditor(FileEditorManagerImpl.java:1239)
	at com.intellij.openapi.fileEditor.FileEditorManager.openEditor(FileEditorManager.java:222)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInAnyFileEditor(FileNavigatorImpl.java:81)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditor(FileNavigatorImpl.java:62)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditorOrNativeApp(FileNavigatorImpl.java:47)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigate(FileNavigatorImpl.java:30)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:91)
	at com.intellij.psi.impl.PsiElementBase.navigate(PsiElementBase.java:196)
	at com.intellij.codeInsight.navigation.NavigationUtil.lambda$openFileWithPsiElement$2(NavigationUtil.java:177)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:170)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:263)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:273)
	at com.intellij.util.OpenSourceUtil.navigateToSource(OpenSourceUtil.java:119)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:74)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:58)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:51)
	at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:19)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:172)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:166)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:394)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:44)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intel [...]

2021-08-19 14:46 UTC, Malyuk-A approved these changes
Code looks good. 👍

(The only thing I could find that might be changed are some very minor "typos/redundancies" in the comments.

2021-08-19 14:46 UTC, Malyuk-A commented on src/main/resources/i18n/OrionBundle_de.properties
> +orion.error.exercise.moduleFailed=Automatische Modul-Konfiguration ist fehlgeschlagen. Mehrere Module gefunden. Konfigure sie manuell unter File->Project Structure->Modules
```suggestion
orion.error.exercise.moduleFailed=Automatische Modul-Konfiguration ist fehlgeschlagen. Mehrere Module gefunden. Konfiguriere diese manuell unter File->Project Structure->Modules
```

2021-08-19 14:46 UTC, Malyuk-A commented on src/main/java/de/tum/www1/orion/util/OrionFileUtils.kt
> +     * @param entry entry to extract
```suggestion
     * @param entry to extract
```

2021-08-19 14:46 UTC, Malyuk-A commented on src/main/java/de/tum/www1/orion/ui/assessment/OrionGutterIconController.kt
> + * @property line line the gutter icon is in
```suggestion
 * @property line the gutter icon is in
```
This might be just your style so this is just a small nitpick.

2021-08-24 15:25 UTC, julian-christl requested changes
Add a head bar to distinguish between Assessment and Text editor

2021-08-24 15:47 UTC, MaisiKoleni requested changes
Found issues during testing:
1. The assessor can add multiple feedback elements to a single line, which is not supported by Artemis and cannot be displayed.
2. When overriding the local feedback with the updated version from Artemis (Orion page refresh), Orion does not preserve the active editor but will switch to the rightmost one.
3. Assess next submission does not do anything in no submissions are left to assess (some message missing).

2021-08-30 22:40 UTC, julian-christl requested changes
I'd suggest renaming "Bearbeitungsmodus" to "Code Editor"-
Because currently both have similar lengths and start with "B" so you actually have to read where you are which is exactly what we wanted to prevent with this header.

If it's possible, you could also colour the assessment header e.g. with an Artemis blue. This would make it more intuitive. But the first change would be enough for now if it's too complicated or not possible.

Nevertheless, please add a screenshot to this fix because I don't think we need a manual test with deployment and plugin installation for this one.

2021-09-01 16:55 UTC, MDK5 commented on src/main/resources/i18n/OrionBundle_de.properties
> +orion.exercise.editMode=Bearbeitungsmodus
```suggestion
orion.exercise.editMode=Code Editor
```

2021-09-02 14:50 UTC, julian-christl approved these changes
The issue was resolved. Not retest since it was only a renaming.

2021-09-04 19:57 UTC, FlorianGlombik approved these changes
The purpose of this PR is fulfilled and the described functionality works.

Besides the known usability issues of the assessment text box regarded to shortcuts as `strg` + `c` / `strg` + `v` / `backspace` I only found two minor issues that can also be fixed in a follow-up PR:
- Multiple assessment comments can be added in one line if the comment is not saved
![image](https://user-images.githubusercontent.com/63976129/132106486-acfe8dbc-dc12-4274-ba19-2e0804f254e1.png)
- The anonymization does not work properly for the git history 
![image](https://user-images.githubusercontent.com/63976129/132106508-4122468c-f7a0-4b3b-90fb-fec730340b28.png)

2021-09-04 19:59 UTC, MDK5 commented
> 
> 
> The purpose of this PR is fulfilled and the described functionality works.
> 
> Besides the known usability issues of the assessment text box regarded to shortcuts as `strg` + `c` / `strg` + `v` / `backspace` I only found two minor issues that can also be fixed in a follow-up PR:
> 
>     * Multiple assessment comments can be added in one line if the comment is not saved
>       ![image](https://user-images.githubusercontent.com/63976129/132106486-acfe8dbc-dc12-4274-ba19-2e0804f254e1.png)
> 
>     * The anonymization does not work properly for the git history
>       ![image](https://user-images.githubusercontent.com/63976129/132106508-4122468c-f7a0-4b3b-90fb-fec730340b28.png)

The former one will be addressed in a follow-up, the later one is unrelated to this PR and will have to be addressed on a separate occasion

2021-09-29 21:00 UTC, merged